name: Build Windows Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          pushImage: false
          image: user/app
          tags: latest
          registry: docker.io
